# Generated by Django 5.1.1 on 2024-11-01 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id_dosen', models.AutoField(primary_key=True, serialize=False)),
                ('nama_dosen', models.CharField(max_length=255)),
                ('departemen', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('jabatan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id_mahasiswa', models.AutoField(primary_key=True, serialize=False)),
                ('nama_mahasiswa', models.CharField(max_length=255)),
                ('program_studi', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tahun_masuk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id_semester', models.AutoField(primary_key=True, serialize=False)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('nama_semester', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id_mata_kuliah', models.AutoField(primary_key=True, serialize=False)),
                ('nama_mata_kuliah', models.CharField(max_length=255)),
                ('sks', models.IntegerField()),
                ('semester', models.CharField(max_length=50)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah', to='Dosen.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluasi',
            fields=[
                ('id_evaluasi', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_evaluasi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('komentar', models.TextField()),
                ('tanggal_evaluasi', models.DateField()),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi', to='Dosen.dosen')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi', to='Dosen.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='Pengajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=50)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajaran', to='Dosen.dosen')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajaran', to='Dosen.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='PengambilanMataKuliah',
            fields=[
                ('id_pengambilan', models.AutoField(primary_key=True, serialize=False)),
                ('tahun_akademik', models.CharField(max_length=9)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah_diambil', to='Dosen.mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengambilan', to='Dosen.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianKinerja',
            fields=[
                ('id_penilaian', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_kinerja', models.DecimalField(decimal_places=2, max_digits=4)),
                ('komentar', models.TextField()),
                ('tanggal_penilaian', models.DateField()),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_kinerja', to='Dosen.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_terima', to='Dosen.mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_kinerja', to='Dosen.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('komentar', models.TextField()),
                ('tanggal_feedback', models.DateField()),
                ('evaluasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dosen.penilaiankinerja')),
            ],
        ),
    ]
